apiVersion: v1
kind: Service
metadata:
  name: todoapp-clusterip-svc
  namespace: todoapp
spec:
  selector:
    app: todolist
  ports:
    - protocol: TCP
      port: 80     
      targetPort: 8000 
  type: ClusterIP