apiVersion: v1
kind: Pod
metadata:
  name: todoapp-1
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
    - name: todoapp-container
      image: langrafka/todoapp:3.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: READINESS_DELAY
          value: "10"
      livenessProbe:
        httpGet:
          path: /api/liveness/
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /api/readiness/
          port: 8080
        initialDelaySeconds: 12 
        periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  name: todoapp-2
  namespace: todoapp
  labels:
    app: todolist
spec:
  containers:
    - name: todoapp-container
      image: langrafka/todoapp:3.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: READINESS_DELAY
          value: "10"
      livenessProbe:
        httpGet:
          path: /api/liveness/
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 5
      readinessProbe:
        httpGet:
          path: /api/readiness/
          port: 8080
        initialDelaySeconds: 12
        periodSeconds: 5